#!/usr/bin/php
<?php

// Copyright 2010–2012, David Öhlin
// GNU GPL 3.0 or later

$output = '';

$sm = @file_get_contents("sitematrix.xml");

$p = -1;
while(TRUE)
{
	//
	// Find language block
	//
	$p = strpos($sm, '<language ', $p+1);
	if($p === FALSE) break;
	
	$e = strpos($sm, '</language>', $p+10);
	if($e === FALSE) break;
	
	$lb = substr($sm, $p, $e-$p);
	
	//
	// Language block info
	//
	$q = strpos($lb, 'code="');
	if($q === FALSE) continue;
	$q+= 6;
	
	$r = strpos($lb, '"', $q);
	if($r === FALSE) continue;
	
	$lang = substr($lb, $q, $r-$q);
	
	$q = strpos($lb, 'name="', $q);
	if($q === FALSE) continue;
	$q+= 6;
	
	$r = strpos($lb, '"', $q);
	if($r === FALSE) continue;
	
	$langname = substr($lb, $q, $r-$q);
	
	//
	// Loop through each site
	//
	$output.= "// " . $lang . " (" . $langname . ")\n";
	while(TRUE)
	{
		$q = strpos($lb, '<site url="', $r+1);
		if($q === FALSE) break;
		$q+= 11;
		
		$r = strpos($lb, '"', $q);
		if($r === FALSE) break;
		
		$siteurl = substr($lb, $q, $r-$q);
		
		$q = strpos($lb, 'code="', $r+1);
		if($q === FALSE) break;
		$q+= 6;
		
		$r = strpos($lb, '"', $q);
		if($r === FALSE) break;
		
		$sitecode = substr($lb, $q, $r-$q);
		if($sitecode == "wiki") $sitecode = "wikipedia";
		$sitecode = ucfirst($sitecode);
		
		$output.= "\$sites[] = Array(\n"
			. "    \"lang\" => \"" . $lang . "\",\n"
			. "    \"langname\" => \"" . $langname . "\",\n"
			. "    \"siteurl\" => \"" . $siteurl . "\",\n"
			. "    \"sitecode\" => \"" . $sitecode . "\");\n";
	}
	$output.= "\n";
	$p = $e;
}

echo "<?php\n\n"
	. "// This list was generated by 'siteupdater.php' and the 'update.sh' script\n\n"
	. $output
	. "?>";

?>
